spring.profiles.active: develop
server:
  port: 8090

resilience4j:
  bulkhead:
    instances:
      stripeService:
        max-concurrent-calls: 10
        max-wait-duration: 500ms

---
spring:
  config:
    activate:
      on-profile: develop
  h2:
    console:
      enabled: true
  jpa:
    show_sql: true
    database: H2
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;IGNORECASE=TRUE
    initialize: false
stripe.simulator.charges-uri: https://sandbox.playtomic.io/v1/stripe-simulator/charges
stripe.simulator.refunds-uri: https://sandbox.playtomic.io/v1/stripe-simulator/payments/{payment_id}/refunds

stripe.simulator.timeout-in-milliseconds: 3000
stripe.simulator.number-of-threads: 4
stripe.simulator.number-of-concurrent-calls: 4
---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    show_sql: false
    database: H2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;IGNORECASE=TRUE
    initialize: false
stripe.simulator.charges-uri: http://localhost:9999
stripe.simulator.refunds-uri: http://localhost:9999

stripe.simulator.timeout-in-milliseconds: 1000
stripe.simulator.number-of-threads: 2
stripe.simulator.number-of-concurrent-calls: 2
